# cpython (stdlib) version as present in current pypy
python_version:
# - 3.6.12
# - 3.7.12
# - 3.8.16
- 3.9.18
# Python 3.8 got dropped as of PyPy 7.3.12
version:
# - 7.3.11
- 7.3.15

zip_keys:
  -
    - python_version
    - version

# override python-variants from global pinning as rerender otherwise needlessly
# creates duplicate CI jobs based on picking up something from meta.yaml
python:
- "3.10.* *_cpython"
# needs to override some other zipped keys as well
numpy:
- "1.22"
python_impl:
- cpython
